### ISSUE TITLE
AlexElec.tv TVlink 

### ISSUE THREAD

**Issue by siliconhippy** [7Ji/7ji.github.io#1]
Hi there 🤠

Was directed from ophub/Armbian.
Very interesting Amlogic work.

Have you seen AlexElec.tv, a fork of Coreelec that has an interesting streaming tool: TVlink Server and PVR client, based on streamlink ?

**Comment by 7Ji** [comment]
I know about AlexELEC but never used it. For x86 I would use the upstream LibreELEC and for aml I would use the upstream CoreELEC. 

I also don't have interest in TV or PVR stuffs on Kodi, I only watch movies and TV series from my server with it. I'm living in China and the IPTV service is pretty closed and I have to use the box bundled with the IPTV service to watch channels.

**Comment by siliconhippy** [comment]
Ok thanks!

1. I am in Toronto, Canada so IPTV channels are quite free, from Plex and
Pluto like services, and also YouTube.

So AlexElec.tv TVlink is very useful. I use IPTV Merge addon to stream Plex
and Pluto via IPTV Simple PVR, and TVlink for direct YouTube and other
streaming channels.

YouTube Kodi plugin sometimes has issues but TVlink streamlink channels
preprocess is good.

2. What do you think of DietPi vs Armbian?

Their website lists many comparisons with Armbian and Debian, and they say
they also use Armbian kernels where needed.

Will Kodi stream better on Coreelec/ Libreelec than on DietPi for A) x86
and B) Amlogic devices ? Or should we expect same performance?

3. I ask because I still don't understand about modified kernel in
Coreelec, e.g , 3.14.29 that was supposed to contain Amlogic proprietary
blob for video efficiency?

How about newer kernels ? Is Coreelec here still better for Amlogic than
Libreelec ( mostly cheap tv boxes)?

For example I have problems with the newer Kodi 20+ builds of
AlexElec/Coreelec vs older Kodi 18 builds ( AlexElec 3.3.5 S9xx Dual boot.)

Maybe this is because I am using a weak processor like S905w ( x96mini
2/16GB tv box.) But I suspect the same issues with older S905xx series.

4. The problem with *ELEC distros are that the rootfs is read only.

Even with #installentware many packages will not run properly, I hear.

And my goal is to be able to manage *ELEC and x86/ARM Linux devices behind
NAT remotely via say, Meshcentral.com...

Meshcentral meshagent cannot be installed on *ELEC unluckily because the
root is 64 bit and the Kodi System on top is 32 bit.

Do you have a hack for this 🤠?

Also there are related small projects you might be interested in...

I might be able to make small donations, if you can accept international
payments like wise.com or PayPal.

Cheers 😺,
Shippy.
----

**Comment by 7Ji** [comment]
If you're already in the territory of all-around distros then you can really just build a media center using it, with custom kernel and Kodi builds of course. 

I don't have opinion on DietPi vs Armbian, as I only use Arch Linux on x86 and Arch Linux ARM on AArcch64 bare-metal and Debian/Ubuntu in containers/VMs. The only exception is a HK1 RBox X4 I use as media center on which I flashed the [HybridELEC Android + CoreELEC + EmuELEC triple boot image](https://github.com/7Ji/HybridELEC/tree/android-burning#hk1-rbox-x4) on eMMC.

For all the features you can just add them into your system with any distro since they are all just Linux under the hood, albeit Arch puts less struggles on the way as the devs don't decide any config and packages for you beforehand.

About the Aml kernel, 3.14.29 is already well in the past. It's the era for their 5.4 kernel, used in CoreELEC's Amlogic-ne project. The reason Amlogic kernel differs a lot from the mainline is that they provide the whole SoC + dev ref board design + kernel + media modules + Android ref AOSP in a "all-in-one package" style. For a new SoC they would pull the newest AOSP kernel (or keep using the last one if Google hasn't forced them by shifting the minumum kernel upwards), add their drivers and proprietary stuffs, update their video-related modules, and send the whole thing to board designers. So, we have these well-known Aml kernels out in the wild:
 - 3.14, used for gxbb family (s905)  at first, ported to gxl family (s905x/l/w/d, your s905w is here)
 - 4.9, used for g12a/g12b family (s905x/y2, s922x) at first, ported to sm1 family (s905x/y3)
 - 5.4, used for sc2 family (s905x/y4, s905w2) at first, ported to t4 family, etc

The fact they are pulled from AOSP kernel which is already vastly different from the mainline kernel with a lot of Google's Android-only stuffs, then added a LOT of Amlogic's proprietary codes, means you really shouldn't compare them to the similar version of mainline kernel. 

You can build CE's kernel and Kodi and use them in your system from another distro, I don't think there's any things making them not to work on a non-Android environment. SBC makers like Hardkernel, Khadas all have boards based on Amlogic SoCs and they release their "Debian", "Armbian", etc with the Amlogic kernel and you can definitely do it too. If you don't want to do it by yourself, AFAIK, OSMC is another project like CoreELEC that uses the Aml kernel and functions like a bare-minumum Kodi OS, but it's based on Ubuntu so has a writtable root.

**Comment by siliconhippy** [comment]
1. I really appreciate your specific SoC kernel details which I have not
heard from anybody else so far ☺️.

Also very good communication skills for a "foreign" tech person and dev 👍

Yes I have seen several HK1 box YouTube videos saying it works great with
retro games and streaming.

2. Unluckily I am not a dev, but with a product manager background +
hobbyist. So I cannot build a kernel or understand various nuances.

Just have an overall view ....so any insights are welcome 🤗.

I have two goals: build an efficient master Linux image(s) of Kodi and
other apps with custom settings; and second, be able to remote manage these
devices with custom image installed on devices ( PCs or tv boxes), usually
behind NAT, on the Cloud.

Of course some devices could be servers ( e.g., Jellyfin, Plex) in the
local network that connects to client devices in same or sub networks.

3. So now that Amlogic is clear in terms of various SoC support:

A. What osmc versions can you use for the Amlogic SoCs: gxbb, gxl, etc ?

Will osmc run ok on above SoC generic tv boxes, or is osmc tailored for its
own tv box brand?

Of course the advantage is writable rootfs.

Will osmc performance for above AML SoCs be same or very close to that for
Coreelec?

B. Do other SoCs like Allwinner and Rockchip also have custom kernels?

In either case, will OSMC work with AW and RK nicely, or is OSMC only for
Amlogic like CoreElec?

My main concern here is video streaming hardware acceleration support,
which is critical for weaker chipsets like S905w, S905, with or without
custom kernels !

 These SoCs are widely used for cheaper tv boxes, which are easier to gift
to people or replace. Some tv boxes can be with higher SoCs.

Here I only worry about 720/1080p streaming, not higher. And premium
features like HDR are not necessary.

4. Are you familiar with meshcentral.com ? Very nice website with a test
server included ( top right yellow button) and great YouTube videos series.

What I want to do is remote manage my devices for friends/ family/
neighbors etc.

A. The basic theme is that I, as "admin" build an efficient AlexElec or
other distro based master image with my favorite addons and skins and Kodi
+ distro settings ( e.g., cron, networking+ remote management.)

Then this master image can be installed on various PCs and TV boxes,
usually at home behind NAT, by "users."

B. Upon first boot, each device user types in a user/password that goes to
Meshcentral server as device *user* id, so each device appearing in
Meshcentral server page can be individually identified for remote
operations by admin, requested by individual users ( via text, email,
messaging to admin.)

Meshcentral also allows, via DNS)web relay/ tcp port forwarding, accessing
management GUI panels for servers installed on behind NAT hardware ( e.g ,
Plex.)

C. Furthermore, some remote operations could be automated via say, Ansible,
operating on admin built and managed database of users ( username,
password, phone, email, usage quota, etc.)

Cheers 😺,
Shippy.
----

**Comment by 7Ji** [comment]
The scenario you planned is too complicated and should be broken down to multiple small pieces. And even then most of them is out of my sight and time-burning for a one-man dev: I don't have interest in them nor would I work on them, I only work on things I like.

You also brought up too many questions in a single issue, this is not how Github issue should be used. I'm unable to track each of them seperately. Please break them into multiple issues instead.

And I don't think it's a clean thing to prepare your distribute & watch "distro" like how you describe it. I don't want to get involved with piracy issues while multi-client media center is easy to get involved with that.

Closed as not planned, since this has really nothing to do with my blog.
